import { NgModule } from '@angular/core';

import {
    MatButtonModule,
    MatInputModule,
    MatFormFieldModule,
    MatCardModule,
    MatDividerModule,
    MatGridListModule,
    MatListModule,
    MatIconModule,
    MatSnackBarModule,
    MatTooltipModule,
    MatToolbarModule,
    MatTableModule,
    MatProgressSpinnerModule,
    MatStepperModule,
    MatCheckboxModule,
    MatSidenavModule,
    MatDialogModule,
    MatChipsModule,
    MatDatepickerModule,
    MatRadioModule,    
    MatRippleModule,
    MatMenuModule,
    MatSelectModule,
    MatPaginatorModule,
    

} from '@angular/material'

@NgModule({
    imports:[
        MatButtonModule,
        MatInputModule,
        MatFormFieldModule,
        MatCardModule,
        MatDividerModule,
        MatGridListModule,
        MatListModule,
        MatIconModule,
        MatSnackBarModule,
        MatTooltipModule,
        MatToolbarModule,
        MatTableModule,
        MatProgressSpinnerModule,
        MatStepperModule,
        MatCheckboxModule,
        MatSidenavModule,
        MatDialogModule,
        MatChipsModule,
        MatDatepickerModule,
        MatRadioModule,
        MatRippleModule,
        MatMenuModule,
        MatSelectModule,
        MatPaginatorModule,
        MatGridListModule
    ],
    exports:[
        MatButtonModule,
        MatInputModule,
        MatFormFieldModule,
        MatCardModule,
        MatDividerModule,
        MatGridListModule,
        MatListModule,
        MatIconModule,
        MatSnackBarModule,
        MatToolbarModule,
        MatTooltipModule,
        MatTableModule,
        MatProgressSpinnerModule,
        MatStepperModule,
        MatCheckboxModule,
        MatSidenavModule,
        MatDialogModule,
        MatChipsModule,
        MatDatepickerModule,
        MatRadioModule,
        MatRippleModule,
        MatMenuModule,
        MatSelectModule,
        MatPaginatorModule,
        MatGridListModule
    ]
})

export class MetarialModule {}